name: Test Workflow

on: push 

jobs:
    say_hello:
        name: Say hello from CI
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4
         
            - name: Say hello
              run: echo Hello from CI
        